#!/usr/bin/env python
# coding: utf-8

#read input
inp = open("inp/input_01.txt").read().splitlines()
inp = [int(i) for i in inp]


### Part 1

suma = 0
for i in range(1,len(inp)):
    if inp[i] > inp[i-1]:
        suma += 1

print("Result for part 1: ", suma)  # 1602


### Part 2

suma2 = 0
for i in range(3,len(inp)):
    window_previous = inp[i-1] + inp[i-2] + inp[i-3]
    window_sum = inp[i] + inp[i-1] + inp[i-2]
    if window_sum > window_previous:
        suma2 += 1

print("Result for part 2: ", suma2)  # 1633
